/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef query_engin_CONSTANTS_H
#define query_engin_CONSTANTS_H

#include "query_engin_types.h"



class query_enginConstants {
 public:
  query_enginConstants();

};

extern const query_enginConstants g_query_engin_constants;



#endif
