/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "query_engin_constants.h"



const query_enginConstants g_query_engin_constants;

query_enginConstants::query_enginConstants() {
}



